orm-pack

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -64,16 +64,17 @@ jobs:
             restore-keys: ${{ runner.os }}-composer-
 
         - name: Install Composer dependencies
-          run: composer install
+          run: composer install --no-progress --prefer-dist --optimize-autoloader
 
         - run: composer require symfony/runtime 
 
         - name: Run Migration && Load Fixtures
           run: |
+            composer require --dev symfony/orm-pack
             php bin/console doctrine:database:drop --if-exists --force --env=test
             php bin/console doctrine:database:create --if-not-exists --env=test
             php bin/console doctrine:schema:update --env=test --force || echo "No migrations found or schema update failed"
-            # php bin/console doctrine:migrations:migrate -y --env=test || echo "No migrations found or migration failed"
+            php bin/console doctrine:migrations:migrate -y --env=test || echo "No migrations found or migration failed"
             php bin/console doctrine:fixtures:load --no-interaction
           env:
            DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
